services:
  - type: web
    name: telegram-scheduler-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false